name: cs182

channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - ipykernel
  - matplotlib
  - numpy
  - pandas
  - pandas
  - pip
  - pylint
  - pytest
  - scipy
  - tqdm
  - pip:
    - simpy
